spring:
  application:
    name: wity
  profiles:
    include:
      - "db"
      - "secure"
    active:
      - "local"

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        use_sql_comments: true # hibernate? ???? ??? ????
        format_sql: true # hibernate? ???? ??? ???
